[package]
name = "fedimint-unknown-common"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-unknown is a fedimint module that doesn't have any client side implementation."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_unknown_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.77"
bitcoin_hashes = "0.11.0"
erased-serde = "0.4"
futures = "0.3"
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
rand = "0.8"
serde = { version = "1.0.197", features = [ "derive" ] }
thiserror = "1.0.58"
tracing = "0.1.40"
