[package]
name = "fedimint-meta-client"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-meta is a meta consensus fedimint module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_meta_client"
path = "src/lib.rs"

[features]
default =[]
cli = ["dep:clap", "dep:serde_json"]

[dependencies]
async-trait = "0.1.73"
anyhow = "1.0.66"
clap = { workspace = true, optional = true }
hex = "0.4.3"
serde_json = { workspace = true, optional = true }
fedimint-meta-common = { version = "=0.3.4-rc.0", path = "../fedimint-meta-common" }
fedimint-client = { version = "=0.3.4-rc.0", path = "../../fedimint-client" }
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
futures = "0.3"
erased-serde = "0.4"
rand = "0.8.5"
secp256k1 = "0.24.2"
serde = {version = "1.0.149", features = [ "derive" ] }
strum = "0.24"
strum_macros = "0.24"
tracing = "0.1.37"
thiserror = "1.0.39"
threshold_crypto = { workspace = true }
