[package]
name = "fedimint-webkv"
version = {workspace = true}
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-webkv provides a IndexedDB-based database implementation for Fedimint."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_webkv"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
fedimint-core = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
webkv = { git = "https://github.com/elsirion/webkv" }

[dev-dependencies]
tempfile = "3.10.1"
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }

[target.'cfg(not(target_family="wasm"))'.dependencies]
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "sync", "time"] }
