[package]
name = "fedimint-portalloc"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Port allocation utility for Fedimint"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_portalloc"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
fs2 = "0.4.3"
serde = { version = "1.0.197", features = [ "derive" ] }
serde_json = { version = "1.0.114", features = ["preserve_order"] }
tracing = "0.1.40"
rand = "0.8"
dirs = "5.0.1"
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
