[package]
name = "fedimint-gateway-cli"
version = "0.3.4-rc.0"
edition = "2021"
license = "MIT"
readme = "../../README.md"
description = "CLI tool to control lightning gateway"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gateway-cli"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.77"
axum = "0.7.4"
axum-macros = "0.4.1"
bitcoin = { version = "0.29.2", features = ["serde"] }
clap = { version = "4.5.2", features = ["derive", "std", "help", "usage", "error-context", "suggestions"], default-features = false }
ln-gateway = { version = "=0.3.4-rc.0", package = "fedimint-ln-gateway", path= "../ln-gateway" }
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
fedimint-logging = { version = "=0.3.4-rc.0", path = "../../fedimint-logging" }
reqwest = { version = "0.11.26", features = [ "json", "rustls-tls" ], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.114"
tokio = {version = "1.36", features = ["full"]}
tracing = { version = "0.1.40", default-features = false, features= ["log", "attributes", "std"] }
url = { version = "2.5.0", features = ["serde"] }
clap_complete = "4.5.1"

[build-dependencies]
fedimint-build = { version = "=0.3.4-rc.0", path = "../../fedimint-build" }
