[package]
name = "fedimint-meta-common"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-meta is a meta-consensus fedimint module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_meta_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
bitcoin_hashes = "0.11.0"
erased-serde = "0.4"
hex = "0.4.3"
futures = "0.3"
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
rand = "0.8"
serde = { version = "1.0.149", features = [ "derive" ] }
serde_json = "1.0.91"
secp256k1 = "0.24.2"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.39"
tracing = "0.1.37"
threshold_crypto = { workspace = true }
