[package]
name = "fedimint-server"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-server' facilitates federated consensus with atomic broadcast and distributed configuration."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_server"
path = "src/lib.rs"

[dependencies]
fedimint-aead = { version = "=0.3.4-rc.0", path = "../crypto/aead" }
anyhow = "1.0.81"
async-channel = "2.2.0"
async-trait = "0.1.77"
bincode = "1.3.3"
bitcoin = "0.29.2"
bitcoin_hashes = "0.11.0"
bytes = "1.5.0"
futures = "0.3.30"
hex = "0.4.3"
itertools = "0.12.1"
fedimint-core = { version = "=0.3.4-rc.0", path = "../fedimint-core" }
fedimint-logging = { version = "=0.3.4-rc.0", path = "../fedimint-logging" }
fedimint-metrics = { version = "=0.3.4-rc.0", path = "../fedimint-metrics" }
lazy_static = "1.4.0"
pin-project = "1.1.5"
rand = "0.8"
rcgen = "=0.12.1"
secp256k1-zkp = { version = "0.7.0", features = [ "global-context", "bitcoin_hashes" ] }
rand_chacha = "0.3.1"
serde = { version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.114"
sha3 = "0.10.8"
strum = "0.26"
strum_macros = "0.26"
tar = "0.4.40"
tbs = { package = "fedimint-tbs", version = "=0.3.4-rc.0", path = "../crypto/tbs" }
thiserror = "1.0.58"
tower = { version = "0.4.13", default-features = false }
tracing ="0.1.40"
url = { version = "2.5.0", features = ["serde"] }
threshold_crypto = { workspace = true }
jsonrpsee = { version = "0.22.2", features = ["server"] }
tokio = { version = "1.36.0", features = ["full", "tracing"] }
tokio-stream = "0.1.14"
tokio-rustls = "0.23.4"
tokio-util = { version = "0.7.10", features = [ "codec" ] }
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }
aleph-bft = { package = "fedimint-aleph-bft", version = "0.30.0", default-features = false }
aleph-bft-types = "0.10.0"
bitcoin_30 = { package = "bitcoin", version = "0.30.2" }
bitcoin_hashes_12 = { package = "bitcoin_hashes", version = "0.12.0" }
parity-scale-codec = "3.6.9"


[dev-dependencies]
tempfile = "3.10.1"
fedimint-dummy-common = { path = "../modules/fedimint-dummy-common" }
fedimint-dummy-server = { path = "../modules/fedimint-dummy-server" }
fedimint-testing = { path = "../fedimint-testing" }
fedimint-portalloc = { path = "../utils/portalloc" }
test-log = { version = "0.2", features = [ "trace" ], default-features = false }

[build-dependencies]
fedimint-build = { version = "=0.3.4-rc.0", path = "../fedimint-build" }
