[package]
name = "fedimint-ln-common"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_ln_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.77"
aquamarine = "0.5.0"
bitcoin_hashes = "0.11.0"
bitcoin = { version = "0.29.2", features = [ "rand", "serde"] }
erased-serde = "0.4"
futures = "0.3.30"
itertools = "0.12.1"
lightning = { version = "0.0.118", default-features = false, features = ["no-std"] }
lightning-invoice = { version = "0.26.0", features = [ "serde" ] }
fedimint-client = { version = "=0.3.4-rc.0", path = "../../fedimint-client" }
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
secp256k1 = { version="0.24.3", default-features=false }
serde = {version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.114"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0.58"
threshold_crypto = { workspace = true }
tracing = "0.1.40"
rand = "0.8"
url = { version = "2.5.0", features = ["serde"] }
serde-big-array = "0.5.1"

[dev-dependencies]
tokio = {version = "1.36.0", features = [ "full" ] }
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }
