[package]
name = "fedimint-wallet-client"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_wallet_client"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
aquamarine = "0.5.0"
async-stream = "0.3.5"
async-trait = "0.1.77"
bitcoin = { version = "0.29.2", features = [ "rand", "serde"] }
erased-serde = "0.4"
fedimint-bitcoind = { version = "0.4.0-alpha", path = "../../fedimint-bitcoind", default-features = false, features = ["esplora-client", "bitcoincore-rpc"] }
fedimint-client = { version = "0.4.0-alpha", path = "../../fedimint-client" }
fedimint-core = { version = "0.4.0-alpha", path = "../../fedimint-core" }
fedimint-wallet-common = { version = "0.4.0-alpha", path = "../fedimint-wallet-common" }
futures = "0.3"
miniscript = { version = "10.0.0", features = [ "compiler", "serde" ] }
impl-tools = "0.10.0"
rand = "0.8"
secp256k1 = { version = "0.24.3", features = [ "serde" ] }
serde = { version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.114"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["sync", "rt"] }
tracing ="0.1.40"
url = "2.5.0"
validator = { version = "0.17", features = ["derive"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }
