[package]
name = "fedimint-empty-server"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-empty is a empty fedimint module, good template for a new module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_empty_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.77"
erased-serde = "0.4"
futures = "0.3"
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
fedimint-empty-common = { version = "=0.3.4-rc.0", path = "../fedimint-empty-common" }
serde = { version = "1.0.197", features = [ "derive" ] }
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0.58"
tracing = "0.1.40"
