[package]
name = "fedimint-ln-gateway"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln-gateway sends/receives Lightning Network payments on behalf of Fedimint clients"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ln_gateway"
path = "src/lib.rs"

[[bin]]
name = "gatewayd"
path = "src/bin/gatewayd.rs"

[[bin]]
name = "gateway-cln-extension"
path = "src/bin/cln_extension.rs"

[[test]]
name = "gatewayd-integration-tests"
path = "tests/integration_tests.rs"

[dependencies]
anyhow = "1.0.81"
async-stream = "0.3.5"
async-trait = "0.1.77"
axum = "0.7.4"
axum-macros = "0.4.1"
aquamarine = "0.5.0"
bitcoin = { version = "0.29.2", features = ["serde"] }
bitcoin_hashes = "0.11.0"
clap = { version = "4.5.2", features = ["derive", "std", "help", "usage", "error-context", "suggestions", "env"], default-features = false }
# cln-plugin made semver incompatible change
cln-plugin = "=0.1.7"
cln-rpc = { workspace = true }
fedimint-client = { version = "=0.3.4-rc.0", path = "../../fedimint-client" }
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
fedimint-logging = { version = "=0.3.4-rc.0", path = "../../fedimint-logging" }
fedimint-rocksdb = { version = "=0.3.4-rc.0", path = "../../fedimint-rocksdb" }
fedimint-ln-client = { version = "=0.3.4-rc.0", path = "../../modules/fedimint-ln-client" }
fedimint-ln-common = { version = "=0.3.4-rc.0", path = "../../modules/fedimint-ln-common" }
fedimint-mint-client = { version = "=0.3.4-rc.0", path = "../../modules/fedimint-mint-client" }
fedimint-dummy-client = { version = "=0.3.4-rc.0", path = "../../modules/fedimint-dummy-client" }
fedimint-wallet-client = { version = "=0.3.4-rc.0", path = "../../modules/fedimint-wallet-client" }
futures = "0.3.30"
erased-serde = "0.4"
lightning-invoice = "0.26.0"
prost = "0.12.3"
rand = "0.8"
reqwest = { version = "0.11.26", features = [ "json", "rustls-tls" ], default-features = false }
secp256k1 = "0.24.3"
secp256k1-zkp = { version = "0.7.0", features = [ "serde", "bitcoin_hashes" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.114"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0.58"
tokio = { version = "1.36", features = ["full"] }
tokio-stream = "0.1.14"
tonic = { version = "0.11.0", features = ["transport", "tls"] }
tonic_lnd = { workspace = true }
tower-http = { version = "0.5.2", features = ["cors", "auth"] }
tracing = { version = "0.1.40", default-features = false, features= ["log", "attributes", "std"] }
url = { version = "2.5.0", features = ["serde"] }

[dev-dependencies]
fedimint-dummy-server = { path = "../../modules/fedimint-dummy-server" }
fedimint-dummy-common = { path = "../../modules/fedimint-dummy-common" }
fedimint-unknown-server = { path = "../../modules/fedimint-unknown-server" }
fedimint-unknown-common = { path = "../../modules/fedimint-unknown-common" }
fedimint-ln-client = { path = "../../modules/fedimint-ln-client" }
fedimint-ln-server = { path = "../../modules/fedimint-ln-server" }
fedimint-ln-common = { path = "../../modules/fedimint-ln-common" }
fedimint-mint-client = { path = "../../modules/fedimint-mint-client" }
fedimint-wallet-client = { path = "../../modules/fedimint-wallet-client" }
fedimint-testing = { path = "../../fedimint-testing" }
lightning = "0.0.118"
threshold_crypto = { workspace = true }
assert_matches = "1.5.0"

[build-dependencies]
fedimint-build = { version = "=0.3.4-rc.0", path = "../../fedimint-build" }
tonic-build = "0.11.0"
