[package]
name = "fedimintd"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimintd is the main consensus code for processing transactions and REST API"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[[bin]]
name = "fedimintd"
path = "src/bin/main.rs"

[lib]
name = "fedimintd"
path = "src/lib.rs"

[dependencies]
fedimint-aead = { version = "=0.3.4-rc.0", path = "../crypto/aead" }
ring = "0.17.8"
anyhow = "1.0.81"
async-trait = "0.1.77"
bincode = "1.3.3"
bitcoin = "0.29.2"
bytes = "1.5.0"
clap = { version = "4.5.2", features = ["derive", "std", "help", "usage", "error-context", "suggestions", "env"], default-features = false }
futures = "0.3.30"
itertools = "0.12.1"
jsonrpsee = { version = "0.22.2", features = ["server"] }
fedimint-bitcoind = { version = "=0.3.4-rc.0", path = "../fedimint-bitcoind" }
fedimint-core = { version = "=0.3.4-rc.0", path = "../fedimint-core" }
fedimint-ln-common = { version = "=0.3.4-rc.0", path = "../modules/fedimint-ln-common" }
fedimint-ln-server = { version = "=0.3.4-rc.0", path = "../modules/fedimint-ln-server" }
fedimint-logging = { version = "=0.3.4-rc.0", path = "../fedimint-logging", features = ["telemetry"] }
fedimint-metrics = { version = "=0.3.4-rc.0", path = "../fedimint-metrics" }
fedimint-mint-server = { version = "=0.3.4-rc.0", path = "../modules/fedimint-mint-server" }
fedimint-meta-server = { version = "=0.3.4-rc.0", path = "../modules/fedimint-meta-server" }
fedimint-rocksdb = { version = "=0.3.4-rc.0", path = "../fedimint-rocksdb" }
fedimint-server = { version = "=0.3.4-rc.0", path = "../fedimint-server" }
fedimint-wallet-server = { version = "=0.3.4-rc.0", path = "../modules/fedimint-wallet-server" }
fedimint-unknown-server = { version = "=0.3.4-rc.0", path = "../modules/fedimint-unknown-server" }
fedimint-unknown-common = { version = "=0.3.4-rc.0", path = "../modules/fedimint-unknown-common" }
rand = "0.8"
rcgen = "=0.12.1"
secp256k1-zkp = { version = "0.7.0", features = [ "global-context", "bitcoin_hashes" ] }
serde = { version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.114"
sha3 = "0.10.8"
tbs = { package = "fedimint-tbs", version = "=0.3.4-rc.0", path = "../crypto/tbs" }
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full", "tracing"] }
tokio-rustls = "0.23.4"
tokio-util = { version = "0.7.10", features = [ "codec" ] }
tracing ="0.1.40"
url = { version = "2.5.0", features = ["serde"] }
threshold_crypto = { workspace = true }

# setup dependencies
axum = { version = "0.7.4", default-features = false, features = [ "form", "tokio" ] }
http = "1.1"
http-body = "1.0"
hyper = { version = "1.2", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
console-subscriber = "0.2.0"

[build-dependencies]
fedimint-build = { version = "=0.3.4-rc.0", path = "../fedimint-build" }
