[package]
name = "fedimint-ln-server"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_ln_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.77"
bincode = "1"
bitcoin_hashes = "0.11.0"
erased-serde = "0.4"
futures = "0.3.30"
itertools = "0.12.1"
lightning = "0.0.118"
lightning-invoice = { version = "0.26.0", features = [ "serde" ] }
fedimint-bitcoind = { version = "=0.3.4-rc.0", path = "../../fedimint-bitcoind" }
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
fedimint-ln-common = { version = "=0.3.4-rc.0", path = "../fedimint-ln-common" }
fedimint-metrics = { version = "=0.3.4-rc.0", path = "../../fedimint-metrics" }
secp256k1 = { version="0.24.3", default-features=false }
serde = {version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.114"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0.58"
threshold_crypto = { workspace = true }
tokio = { version = "1.36", features = ["full"] }
tracing = "0.1.40"
rand = "0.8"
url = { version = "2.5.0", features = ["serde"] }
fedimint-server = { version = "=0.3.4-rc.0", path = "../../fedimint-server" }

[dev-dependencies]
assert_matches = "1.5.0"
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tokio = {version = "1.36.0", features = [ "full" ] }
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }
