[package]
name = "fedimint-testing"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-testing provides a library of shared objects and utilities for testing fedimint components"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_testing"
path = "src/lib.rs"


[dependencies]
anyhow = "1.0.81"
async-stream = "0.3.5"
async-trait = "0.1.77"
bitcoin = "0.29.2"
bitcoincore-rpc = "0.16.0"
clap = { version = "4.5.2", features = ["derive", "std", "help", "usage", "error-context", "suggestions" ], default-features = false }
cln-rpc = { workspace = true }
fedimint-core  = { version = "=0.3.4-rc.0", path = "../fedimint-core" }
fedimint-client  = { version = "=0.3.4-rc.0", path = "../fedimint-client" }
fedimint-server  = { version = "=0.3.4-rc.0", path = "../fedimint-server" }
fedimint-bitcoind = { version = "=0.3.4-rc.0", path = "../fedimint-bitcoind" }
fedimint-logging = { version = "=0.3.4-rc.0", path = "../fedimint-logging" }
fedimint-rocksdb = { version = "=0.3.4-rc.0", path = "../fedimint-rocksdb" }
fs-lock = "0.1.3"
lazy_static = "1.4.0"
ln-gateway = { version = "=0.3.4-rc.0", package = "fedimint-ln-gateway", path = "../gateway/ln-gateway" }
futures = "0.3"
lightning-invoice = "0.26.0"
tempfile = "3.10.1"
secp256k1 = "0.24.3"
secp256k1-zkp = { version = "0.7.0", features = [ "global-context", "bitcoin_hashes" ] }
serde = { version = "1.0.197", features = [ "derive" ] }
tracing ="0.1.40"
rand = "0.8"
tokio-rustls = "0.23.4"
tokio = { version = "1.36.0", features = ["full", "tracing"] }
tokio-stream = "0.1.14"
tonic_lnd = { workspace = true }
url = "2.5.0"
fedimint-portalloc = { version = "=0.3.4-rc.0", path = "../utils/portalloc" }
