[package]
name = "fedimint-ln-tests"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln-tests contains integration tests for the lightning module"
license = "MIT"
publish = false

[[test]]
name = "fedimint_ln_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = "1.0.81"
assert_matches = "1.5.0"
bitcoin = { version = "0.29.2", features = [ "rand", "serde"] }
bitcoin_hashes = "0.11.0"
fedimint-bitcoind = { path = "../../fedimint-bitcoind" }
fedimint-dummy-common = { path = "../fedimint-dummy-common" }
fedimint-dummy-client = { path = "../fedimint-dummy-client" }
fedimint-dummy-server = { path = "../fedimint-dummy-server" }
fedimint-ln-common = { path = "../fedimint-ln-common" }
fedimint-ln-client = { path = "../fedimint-ln-client" }
fedimint-ln-server = { path = "../fedimint-ln-server" }
fedimint-testing = { path = "../../fedimint-testing" }
fedimint-client = { path = "../../fedimint-client" }
fedimint-core ={ path = "../../fedimint-core" }
fedimint-server = { path = "../../fedimint-server" }
fedimint-logging = { path = "../../fedimint-logging" }
futures = "0.3.30"
lightning-invoice = { version = "0.26.0", features = [ "serde" ] }
threshold_crypto = { workspace = true }
tokio = { version = "1.36.0", features = ["sync"] }
tracing = "0.1.40"
secp256k1 = { version="0.24.3", default-features=false }
serde_json = "1.0.114"
rand = "0.8"
strum = "0.26"
strum_macros = "0.26"
