[package]
name = "fedimint-wallet-common"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_wallet_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.77"
bitcoin = { version = "0.29.2", features = [ "rand", "serde"] }
erased-serde = "0.4"
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
futures = "0.3"
miniscript = { version = "10.0.0", features = [ "compiler", "serde" ] }
miniscript9 = { package = "miniscript", version = "9.0.2" }
impl-tools = "0.10.0"
rand = "0.8"
secp256k1 = { version = "0.24.3", features = [ "serde" ] }
serde = { version = "1.0.197", features = [ "derive" ] }
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["sync"], optional = true }
tracing ="0.1.40"
url = "2.5.0"
validator = { version = "0.17", features = ["derive"] }

[dev-dependencies]
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }
